### ISSUE TITLE
share api

### ISSUE THREAD

**Issue by fengmk2** [QLeelulu/ohlala#18]
类似pocket的api，可以集成到fawave中

http://milnk.com/link/10545#cm-10274

**Comment by QLeelulu** [comment]
如果是实现完整的API，顺便吧 #11 需要的接口也考虑一下

**Comment by fengmk2** [comment]
昨晚看了一下，还没成功跑起来，得先写个goku的hello world了解一下。

**Comment by QLeelulu** [comment]
按照Readme说的去跑应该没问题的吧。
什么错误啊？

2013/1/15 fengmk2 notifications@github.com

> 昨晚看了一下，还没成功跑起来，得先写个goku的hello world了解一下。
> On Jan 15, 2013 2:52 PM, "QLeelulu" notifications@github.com wrote:
> 
> > 如果是实现完整的API，顺便吧 #11 <https://github.com/QLeelulu/ohlala/issues/11
> > 需要的接口也考虑一下
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/QLeelulu/ohlala/issues/18#issuecomment-12255608>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/QLeelulu/ohlala/issues/18#issuecomment-12259934.

## 

@QLeelulu http://weibo.com/qleelulu | FaWave, Net4 Team |
qleelulu@gmail.com | 学海无涯,回头是岸
