### ISSUE TITLE
找回密码功能

### ISSUE THREAD

**Issue by hippasus** [QLeelulu/ohlala#19]
提供找回密码功能

**Comment by QLeelulu** [comment]
疯子，加油！！

**Comment by fengmk2** [comment]
期待！

**Comment by hippasus** [comment]
想通过发送带重置密码链接的邮件来做，相关的发送 email 的 from email & password、 smtp server、 email主题与内容模板等配置信息如何存放比较好？ @QLeelulu @fengmk2 
1. 统一放到 golink/config.go 里面面的话，需要把 config.go 移到一个新的地方，比如 golink/config/ 这个文件夹下去
2. 还是新建个 golink/config/ 文件夹，这下面存放各种配置信息，比如这次的就叫 user_recovery_config.go

个人比较侧重方案 2 :)

**Comment by QLeelulu** [comment]
嗯，同意方案2
